/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TalksRouteImport } from './routes/talks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTalksRouteImport } from './routes/admin.talks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLanguagesRouteImport } from './routes/admin.languages'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminColorsRouteImport } from './routes/admin.colors'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksRoute = TalksRouteImport.update({
  id: '/talks',
  path: '/talks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTalksRoute = AdminTalksRouteImport.update({
  id: '/talks',
  path: '/talks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColorsRoute = AdminColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/talks': typeof TalksRoute
  '/videos': typeof VideosRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talks': typeof AdminTalksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/talks': typeof TalksRoute
  '/videos': typeof VideosRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talks': typeof AdminTalksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/talks': typeof TalksRoute
  '/videos': typeof VideosRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talks': typeof AdminTalksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/talks'
    | '/videos'
    | '/admin/colors'
    | '/admin/courses'
    | '/admin/languages'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/talks'
    | '/admin/users'
    | '/admin/videos'
    | '/api/chat'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin/'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/talks'
    | '/videos'
    | '/admin/colors'
    | '/admin/courses'
    | '/admin/languages'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/talks'
    | '/admin/users'
    | '/admin/videos'
    | '/api/chat'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/companies'
    | '/contact'
    | '/talks'
    | '/videos'
    | '/admin/colors'
    | '/admin/courses'
    | '/admin/languages'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/talks'
    | '/admin/users'
    | '/admin/videos'
    | '/api/chat'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/admin/'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  TalksRoute: typeof TalksRoute
  VideosRoute: typeof VideosRoute
  ApiChatRoute: typeof ApiChatRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks': {
      id: '/talks'
      path: '/talks'
      fullPath: '/talks'
      preLoaderRoute: typeof TalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/talks': {
      id: '/admin/talks'
      path: '/talks'
      fullPath: '/admin/talks'
      preLoaderRoute: typeof AdminTalksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colors': {
      id: '/admin/colors'
      path: '/colors'
      fullPath: '/admin/colors'
      preLoaderRoute: typeof AdminColorsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminColorsRoute: typeof AdminColorsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTalksRoute: typeof AdminTalksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminColorsRoute: AdminColorsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTalksRoute: AdminTalksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  TalksRoute: TalksRoute,
  VideosRoute: VideosRoute,
  ApiChatRoute: ApiChatRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
